#!/bin/bash
STRTOK="strtok.c"
StrtokTest="tests/test_strtok.c"
CC="gcc -Wall -Werror -Wextra -pedantic -std=gnu89 -g -L./bin/ -L./tests/ -I."
echo "strtok() test"
echo "............."
$CC $STRTOK $StrtokTest -o bin/strtok
n=$(echo $?)
if [ $n -ne 0 ]; then
echo "strtok(): Compiling Failed !!!"
exit
fi
#echo Compilation sucess !
#echo "Running strtok() test ..."
bin/strtok
